name: suinocultura_ia
description: App de monitoramento de peso de suÃ­nos com IA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  tutorial_coach_mark: ^1.2.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # HTTP
  http: ^1.1.0
  
  # Camera
  camera: ^0.11.3+1
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.20.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/pig.png
